create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique check (length(btrim(slug)) > 0),
  name text not null check (length(btrim(name)) > 0),
  price_inr integer not null check (price_inr >= 0),
  short_description text not null check (length(btrim(short_description)) > 0),
  image_url text not null check (length(btrim(image_url)) > 0),
  mask_type text not null check (length(btrim(mask_type)) > 0),
  in_stock boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

revoke all on table public.products from anon, authenticated;
grant select, insert, update, delete on table public.products to service_role;
grant usage, select on sequence public.products_id_seq to service_role;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();
